### ISSUE TITLE
powershell generation error : originalString.match is not a function

### ISSUE THREAD

**Issue by erich-wang** [Azure/perks.eventing#7]
I got the error `originalString.match is not a function` during powershell generation for AKS, please advise whether it is swagger spec error or a bug in remodeler?

## Reproduce
```
> git clone -b generation https://github.com/erich-wang/azure-powershell.git
> cd azure-powershell/src/Aks
> autorest-beta.com
```

## Error
```
PS C:\AME\work-azure-powershell\src\Aks> autorest-beta.cmd --debug
AutoRest code generation utility [version: 3.0.6116; node: v10.15.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from C:\Users\eriwan.FAREAST\.autorest\@autorest_core@3.0.6117
   Loading AutoRest core      'C:\Users\eriwan.FAREAST\.autorest\@autorest_core@3.0.6117\node_modules\@autorest\core\dist' (3.0.6117)
   Loading AutoRest extension '@autorest/powershell' (~2.0.295->2.0.307)
   Loading AutoRest extension '@autorest/remodeler' (~2.0.4->2.0.8)
DEBUG [5.17 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [5.17 s]: openapi-document-override/md-override-loader-openapi - START inputs = 0
DEBUG [5.18 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [5.18 s]: swagger-document-override/md-override-loader-swagger - START inputs = 0
DEBUG [5.18 s]: pipeline-emitter - START inputs = 0
DEBUG [5.21 s]: configuration-emitter - START inputs = 0
DEBUG [5.26 s]: pipeline-emitter - END [0.09 s]
DEBUG [5.26 s]: configuration-emitter - END [0.09 s]
DEBUG [10.4 s]: openapi-document/loader-openapi - END [5.23 s]
DEBUG [10.4 s]: openapi-document/individual/transform - SKIPPING
DEBUG [10.4 s]: openapi-document/individual/schema-validator-openapi - SKIPPING
DEBUG [10.4 s]: openapi-document/individual/identity - SKIPPING
DEBUG [10.41 s]: openapi-document-override/md-override-loader-openapi - END [5.24 s]
DEBUG [10.41 s]: swagger-document-override/md-override-loader-swagger - END [5.24 s]
DEBUG [10.42 s]: openapi-document/transform-immediate - START inputs = 17
DEBUG [10.46 s]: openapi-document/transform-immediate - END [0.03 s]
DEBUG [10.8 s]: swagger-document/loader-swagger - END [5.63 s]
DEBUG [10.8 s]: swagger-document/individual/transform - START inputs = 17
DEBUG [10.89 s]: swagger-document/individual/transform - END [0.09 s]
DEBUG [10.9 s]: swagger-document/individual/schema-validator-swagger - START inputs = 17
DEBUG [11.05 s]: swagger-document/individual/schema-validator-swagger - END [0.15 s]
DEBUG [11.05 s]: swagger-document/identity - START inputs = 17
DEBUG [11.06 s]: swagger-document/individual/identity - START inputs = 17
DEBUG [11.06 s]: swagger-document/identity - END [0 s]
DEBUG [11.06 s]: swagger-document/individual/identity - END [0 s]
DEBUG [11.06 s]: openapi-document/openapi-document-converter - START inputs = 17
DEBUG [11.3 s]: openapi-document/openapi-document-converter - END [0.24 s]
DEBUG [11.31 s]: openapi-document/transform - START inputs = 18
DEBUG [11.41 s]: openapi-document/transform - END [0.09 s]
DEBUG [11.41 s]: openapi-document/tree-shaker - START inputs = 18
DEBUG [11.72 s]: openapi-document/tree-shaker - END [0.31 s]
DEBUG [11.72 s]: openapi-document/multi-api-merger - START inputs = 18
DEBUG [13.43 s]: openapi-document/multi-api-merger - END [1.7 s]
DEBUG [13.43 s]: openapi-document/components-cleaner - START inputs = 1
DEBUG [14.17 s]: openapi-document/components-cleaner - END [0.74 s]
DEBUG [14.17 s]: openapi-document/component-modifiers - START inputs = 1
DEBUG [14.17 s]: openapi-document/component-modifiers - END [0 s]
DEBUG [14.18 s]: openapi-document/api-version-parameter-handler - START inputs = 1
DEBUG [14.18 s]: openapi-document/api-version-parameter-handler - END [0 s]
DEBUG [14.18 s]: openapi-document/profile-filter - START inputs = 1
DEBUG [15.7 s]: openapi-document/profile-filter - END [1.51 s]
DEBUG [15.7 s]: openapi-document/model-deduplicator - START inputs = 1
DEBUG [15.7 s]: openapi-document/emitter - START inputs = 1
DEBUG [15.73 s]: openapi-document/emitter - END [0.03 s]
DEBUG [18.11 s]: openapi-document/model-deduplicator - END [2.4 s]
DEBUG [18.11 s]: openapi-document/enum-deduplicator - START inputs = 1
DEBUG [18.25 s]: openapi-document/enum-deduplicator - END [0.13 s]
DEBUG [18.25 s]: openapi-document/subset-reducer - START inputs = 1
DEBUG [18.35 s]: openapi-document/subset-reducer - END [0.1 s]
DEBUG [18.36 s]: openapi-document/quick-check - START inputs = 1
DEBUG [18.36 s]: openapi-document/multi-api/identity - START inputs = 1
DEBUG [18.36 s]: openapi-document/multi-api/identity - END [0 s]
DEBUG [18.36 s]: openapi-document/multi-api/emitter - START inputs = 1
DEBUG [18.36 s]: remodeler - START inputs = 1
DEBUG [18.38 s]: openapi-document/quick-check - END [0.02 s]
DEBUG [18.39 s]: openapi-document/multi-api/emitter - END [0.02 s]

WARNING (UndefinedTypeWithSchema): The schema 'schemas:47' with a undefined type and using allOf is a bit ambigious. This has been auto-corrected to 'type:object'
    - oai3-subset-schema-reduced doc...:1:1

WARNING (UndefinedTypeWithSchema): The schema 'schemas:51' with a undefined type and using allOf is a bit ambigious. This has been auto-corrected to 'type:object'
    - oai3-subset-schema-reduced doc...:1:1
C:\Users\eriwan.FAREAST\.autorest\@autorest_remodeler@2.0.8\node_modules\@autorest\remodeler\dist\plugin-remodeler.js - FAILURE  {} TypeError: originalString.match is not a function
    at getValidEnumValueName (C:\Users\eriwan.FAREAST\.autorest\@autorest_remodeler@2.0.8\node_modules\@autorest\remodeler\interpretations.ts:55:26)
    at values.xmse.values.original.enum.map.each (C:\Users\eriwan.FAREAST\.autorest\@autorest_remodeler@2.0.8\node_modules\@autorest\remodeler\interpretations.ts:100:19)
    at Array.map (<anonymous>)
    at Object.getEnumDefinition (C:\Users\eriwan.FAREAST\.autorest\@autorest_remodeler@2.0.8\node_modules\@autorest\remodeler\interpretations.ts:97:23)
    at Remodeler.copySchema (C:\Users\eriwan.FAREAST\.autorest\@autorest_remodeler@2.0.8\node_modules\@autorest\remodeler\remodeler.ts:220:54)
    at Remodeler.add (C:\Users\eriwan.FAREAST\.autorest\@autorest_remodeler@2.0.8\node_modules\@autorest\remodeler\remodeler.ts:325:12)
    at Remodeler.refOrAdd (C:\Users\eriwan.FAREAST\.autorest\@autorest_remodeler@2.0.8\node_modules\@autorest\remodeler\remodeler.ts:353:19)
    at Remodeler.copySchema (C:\Users\eriwan.FAREAST\.autorest\@autorest_remodeler@2.0.8\node_modules\@autorest\remodeler\remodeler.ts:286:36)
    at Remodeler.add (C:\Users\eriwan.FAREAST\.autorest\@autorest_remodeler@2.0.8\node_modules\@autorest\remodeler\remodeler.ts:325:12)
    at Remodeler.refOrAdd (C:\Users\eriwan.FAREAST\.autorest\@autorest_remodeler@2.0.8\node_modules\@autorest\remodeler\remodeler.ts:353:19)
FATAL: TypeError: originalString.match is not a function
C:\Users\eriwan.FAREAST\.autorest\@autorest_core@3.0.6117\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Plugin remodeler reported failure. / Error: Plugin remodeler reported failure.
    at C:\Users\eriwan.FAREAST\.autorest\@autorest_core@3.0.6117\node_modules\@autorest\core\dist\lib\pipeline\plugins\external.js:26:19
  Error: Plugin remodeler reported failure.
[18.5 s] Shutting Down.
[18.5 s] Exiting.
```

**Comment by fearthecowboy** [comment]
Ok, all the bits that needed to be pushed are fixed -- use `autorest-beta --reset` and the latest autorest remodeler  is fixed:

![image](https://user-images.githubusercontent.com/133736/67226768-9b9a7a80-f3ea-11e9-974d-83c465939a47.png)
